---
branch: master
earliest_version:
collapse_pre_releases: false
stop_at_branch_base: true
sections:
  - [user_visible, User visible changes]
  - [internal, Internal changes]
  - [admin, Administrator Guide]
  - [api, API Guides]
  - [architecture_design, Architecture Design Guide]
  - [cli, Command Line Interface Reference]
  - [config, Configuration Reference]
  - [contributor, Contributor Guide]
  - [deployment, Deployment Guide]
  - [enduser, End User Guide]
  - [ha, High Availability Guide]
  - [installation, Installation Tutorials and Guides]
  - [networking, Networking Guide]
  - [operations, Operations Guide]
  - [security, Security Guide]
  - [training, Training Guides]
  - [translations, Translations]
  - [user, User Guide]
template: |
    ---
    # For each of the following sections, add any changes relating
    # to that section, or remove the section altogether if there
    # are no changes relating to it.
    #
    # All of the list items in each of the following sections are
    # combined when the release notes are rendered, so the text needs
    # to be worded so that it does not depend on any information only
    # available in another section, such as the prelude. This may mean
    # repeating some details.
    #
    # If the relevant section is missing from the below list, please
    # first submit a review adding it to releasenotes/config.yaml.
    # This way we can ensure that we have a consistent set of sections
    # without any duplication.
    prelude: >
        Replace this text with content to appear at the top of the
        section for this release. Not every release note requires a
        prelude. Usually only notes describing major features or
        adding release theme details should have a prelude.
    user_visible:
      - List user-visible changes here.
    internal:
      - List internal changes here.
    admin:
      - List changes to the Administrator Guide here.
    api:
      - List changes to the API Guides here.
    architecture_design:
      - List changes to the Architecture Design Guide here.
    cli:
      - List changes to the Command Line Interface Reference Guide
        here.
    config:
      - List changes to the Configuration Reference here.
    contributor:
      - List changes to the Contributor Guide here.
    deployment:
      - List changes to the Deployment Guide here.
    enduser:
      - List changes to the End User Guide here.
    ha:
      - List changes to the High Availability Guide here.
    installation:
      - List changes to the Installation Tutorials and Guides here.
    networking:
      - List changes to the Networking Guide here.
    operations:
      - List changes to the Operations Guide here.
    security:
      - List changes to the Security Guide here.
    training:
      - List changes to the Training Guides here.
    translations:
      - List changes to the translations here.
    user:
      - List changes to the User Guide here.
